## This configuration was generated by terraform-provider-oci

resource oci_core_internet_gateway export_Internet-Gateway-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "<username>"
    "Oracle-Tags.CreatedOn" = "<time-created>"
  }
  display_name = "Internet Gateway-VCN-01"
  enabled      = "true"
  freeform_tags = {
    "VCN" = "<auto-generated-tag>"
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_vcn export_VCN-01 {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "<username>"
    "Oracle-Tags.CreatedOn" = "<time-created>"
  }
  display_name = "VCN-01"
  dns_label    = "<dns-label>"
  freeform_tags = {
    "VCN" = "<auto-generated-tag>"
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_subnet export_Public-Subnet-VCN-01 {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "<username>"
    "Oracle-Tags.CreatedOn" = "<time-created>"
  }
  dhcp_options_id = oci_core_vcn.export_VCN-01.default_dhcp_options_id
  display_name    = "Public Subnet-VCN-01"
  dns_label       = "<dns-label>"
  freeform_tags = {
    "VCN" = "<auto-generated-tag>"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_VCN-01.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_VCN-01.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_subnet export_Private-Subnet-VCN-01 {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.1.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "<username>"
    "Oracle-Tags.CreatedOn" = "<time-created>"
  }
  dhcp_options_id = oci_core_vcn.export_VCN-01.default_dhcp_options_id
  display_name    = "Private Subnet-VCN-01"
  dns_label       = "<dns-label>"
  freeform_tags = {
    "VCN" = "<auto-generated-tag>"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_Route-Table-for-Private-Subnet-VCN-01.id
  security_list_ids = [
    oci_core_security_list.export_Security-List-for-Private-Subnet-VCN-01.id,
  ]
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_service_gateway export_Service-Gateway-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "<username>"
    "Oracle-Tags.CreatedOn" = "<time-created>"
  }
  display_name = "Service Gateway-VCN-01"
  freeform_tags = {
    "VCN" = "<auto-generated-tag>"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "<service-id>"
  }
  vcn_id = oci_core_vcn.export_VCN-01.id
}

# COMMENT THIS BLOCK
# resource oci_core_private_ip export_VM-01 {
#   defined_tags = {
#     "Oracle-Tags.CreatedBy" = "<username>"
#     "Oracle-Tags.CreatedOn" = "<time-created>"
#   }
#   display_name = "VM-01"
#   freeform_tags = {
#   }
#   hostname_label = "vm-01"
#   ip_address     = "<private-ip>"
#   #vlan_id = <<Optional value not found in discovery>>
#   vnic_id = "<vnic-id>"
# }

resource oci_core_instance export_VM-01_1 {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "DISABLED"
      name          = "Vulnerability Scanning"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Oracle Java Management Service"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "OS Management Service Agent"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Run Command"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Block Volume Management"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    #is_live_migration_preferred = <<Optional value not found in discovery>>
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = var.availability_domain
  #capacity_reservation_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  create_vnic_details {
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "true"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "<username>"
      "Oracle-Tags.CreatedOn" = "<time-created>"
    }
    display_name = "VM-01"
    freeform_tags = {
    }
    hostname_label = "vm-01"
    nsg_ids = [
    ]

    # COMMENT THIS LINE BELOW
    # private_ip             = "<private-ip>" 

    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_Public-Subnet-VCN-01.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "<username>"
    "Oracle-Tags.CreatedOn" = "<time-created>"
  }
  display_name = "VM-01"
  extended_metadata = {
  }
  fault_domain = var.fault_domain
  freeform_tags = {
  }
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>

#   COMMENT THIS BLOCK BELOW
#   launch_options {
#     boot_volume_type                    = "PARAVIRTUALIZED"
#     firmware                            = "UEFI_64"
#     is_consistent_volume_naming_enabled = "true"
#     is_pv_encryption_in_transit_enabled = "true"
#     network_type                        = "PARAVIRTUALIZED"
#     remote_data_volume_type             = "PARAVIRTUALIZED"
#   }

  metadata = {
    "ssh_authorized_keys" = "ssh-rsa <label-for-your-ssh-key>"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.A1.Flex"
  shape_config {
    # baseline_ocpu_utilization = ""  # COMMENT THIS LINE
    memory_in_gbs             = "6"
    # nvmes                     = "0" # COMMENT THIS LINE
    ocpus                     = "1"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    boot_volume_vpus_per_gb = "10"
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.oci_core_instance--source_details-source_id--export_VM-01_1
    source_type = "image"
  }
  state = "RUNNING"
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "<username>"
    "Oracle-Tags.CreatedOn" = "<time-created>"
  }
  display_name     = "Default DHCP Options for VCN-01"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
    "VCN" = "<auto-generated-tag>"
  }
  manage_default_resource_id = oci_core_vcn.export_VCN-01.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "iadoplab071vcn0.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_nat_gateway export_NAT-Gateway-VCN-01 {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "<username>"
    "Oracle-Tags.CreatedOn" = "<time-created>"
  }
  display_name = "NAT Gateway-VCN-01"
  freeform_tags = {
    "VCN" = "<auto-generated-tag>"
  }

#   COMMENT THIS LINE BELOW
#   public_ip_id = "<public-ip-id>"

  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_route_table export_Route-Table-for-Private-Subnet-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "<username>"
    "Oracle-Tags.CreatedOn" = "<time-created>"
  }
  display_name = "Route Table for Private Subnet-VCN-01"
  freeform_tags = {
    "VCN" = "<auto-generated-tag>"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_NAT-Gateway-VCN-01.id
    #route_type = <<Optional value not found in discovery>>
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-iad-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_Service-Gateway-VCN-01.id
    #route_type = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "<username>"
    "Oracle-Tags.CreatedOn" = "<time-created>"
  }
  display_name = "Default Route Table for VCN-01"
  freeform_tags = {
    "VCN" = "<auto-generated-tag>"
  }
  manage_default_resource_id = oci_core_vcn.export_VCN-01.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-Gateway-VCN-01.id
    #route_type = <<Optional value not found in discovery>>
  }
}

resource oci_core_security_list export_Security-List-for-Private-Subnet-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "<username>"
    "Oracle-Tags.CreatedOn" = "<time-created>"
  }
  display_name = "Security List for Private Subnet-VCN-01"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "<auto-generated-tag>"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_default_security_list export_Default-Security-List-for-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "<username>"
    "Oracle-Tags.CreatedOn" = "<time-created>"
  }
  display_name = "Default Security List for VCN-01"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "<auto-generated-tag>"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_VCN-01.default_security_list_id
}

